### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by sahilsharmafrank** [sharma02gaurav/angular-pagination-example#1]
1. mongoDB integration with pagination.
2. validation of form with below mentioned fields: 
  2.1 full_name, phone_no, email, username, url, password, address, male/female radio, interests [ Checkboxes atleast 2 should be checked].
  2.2 dynamically check email & username from server.
  2.3 masking on phone number (xxx-xxx-xxxx)
3. List the details of form submitted above.
    3.1 Pagination + Sorting on email, full_name, username, phone_no
    3.2 searching with sorting and pagination.
4. Soft delete the user.
5. update the selected record.
6. toast / notification message.
7. Make directive (Part-2 ) for showing paginated records.

Note : Use State provider for routing. Proper commenting for controllers and function.

**Comment by ops-gaurav** [comment]
Almost done.. Got stuck up into another task. This task is 70% complete.
Only easy tasks left like searching, soft delete and update.

**Comment by sahilsharmafrank** [comment]
Correct directory structure 
1. Create controller folder
2. Create services folder which will contain all the middlewares for application (ex. passport)
3. Implement passport-jwt && localstratergy
